apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  labels:
    app: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: muhammadhaseem/go_app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1323
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_NAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "haseem123"
          # resources:
          #   requests:
          #     memory: "256Mi"
          #     cpu: "500m"
          #   limits:
          #     memory: "512Mi"
          #     cpu: "1000m"
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 1323
          #     scheme: HTTP
          #   initialDelaySeconds: 30
          #   periodSeconds: 15
          #   timeoutSeconds: 5
          # readinessProbe:
          #   httpGet:
          #     path: /readiness
          #     port: 1323
          #     scheme: HTTP
          #   initialDelaySeconds: 30  # Adjusted delay to account for application startup
          #   periodSeconds: 15
          #   timeoutSeconds: 5  # Increased timeout to account for longer response times
