version: '3.9'

services:
  app:
    container_name: golang
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/golang

    ports:
      - "8080:8080"
    depends_on:
      - db     
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASS=haseem123
      - GIN_MODE=debug
  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "haseem123"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"

volumes:
  postgres_data:
