version: "3.9"

services:
  app:
    container_name: golang
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    networks:
      - backend
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "haseem123"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:
networks:
  backend:
    driver: bridge
